name: Build project and run Lighthouse CI
on: [push]
jobs:
  lhci:
    name: Lighthouse CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          pwd
          npm install
          npm ci
          npm install -g @lhci/cli@0.3.x
          npx lhci autorun
          pwd
      - name: Add comment to PR
        id: loading_lighthouse_comment_to_pr
        uses: marocchino/sticky-pull-request-comment@v2
        with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            append: true 
            header: lighthouse
            message: |
                🚦 Running Lighthouse audit...

